Sync From OpenWebF/webf (#19)
* fix: fix coordinate conversion related to position fixed.

* fix: fix test specs

* fix: fix integration test.

* Fix: fix crash when add property maybe failed on build arguments

* feat: add console.inspect() API for inspecting JavaScript Objects. (#691)

Add a new Console API for inspecting complex JavaScript objects.

Example: 
```javascript
const json = {
    name: 1,
    age: '2',
    map: new Map(),
    set: new Set(),
    fn: function() { return 1; },
    undefined: undefined,
    null: null,
    nest: { nest: {aa: { arr: [1,2,3,4,5]}}}
  };
  json.map['name'] = new Map();
  json.set.add(1);
  json.set.add(2);
  json.map['name']['age'] = [1,2,3,4,5];
  console.inspect(json, 2, 3,4);
```

Result:
```
{
  name: 1, 
  age: '2', 
  map: Map {
    name: Map {
      age: [1, 2, 3, 4, 5]
    }
  }, 
  set: Set {1, 2}, 
  fn: Function {
    length: 0, 
    name: 'fn', 
    prototype: {
      constructor: #
    }
  }, 
  undefined: undefined, 
  null: null, 
  nest: {
    nest: {
      aa: {
        arr: [1, 2, 3, 4, 5]
      }
    }
  }
} 2 3 4
```

* feat: add WebFChildNodeSize widget.

* fix: make listview elements to have WebFChildNodeSize.

* doc: add annotations for WebFChildNodeSize.

* fix: fix text layout error.

* Committing clang-format changes

* WIP: native_value

* fix: fix crashed due to windows malloc.

* feat: native value support in rust

* feat: update rs code gen path

* feat: add navigator

* Update code_linter.yml

* Update code_linter.yml

* Commit from GitHub Actions (Run Code Linter)

* feat: support storage

* feat: add return value for webf function

* Commit from GitHub Actions (Run Code Linter)

* fix: enable return value for module listener

* feat: add needed is methods

* feat: crlf to lf

* fix: release heap string

* fix: fix code linter workflow

* fix: fix linux build

* fix: fix linux build

* Commit from GitHub Actions (Run Code Linter)

* fix: linux build

* feat: use future for async storage

* feat: upgrade intl deps to 0.19.0.

* feat: using std::atomic value types for disposed checks of NativeBindingObject.

---------

Co-authored-by: Penner <penneryu@gmail.com>
Co-authored-by: openwebf-bot <openwebf@openwebf.com>
Co-authored-by: AzureAD\JiaxunWei <jiaxun.wei@keg.com>
Co-authored-by: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Jiaxun Wei <leuisken@gmail.com>