Sync from openwebf/webf (#15)
* Squashed commit of the following:

commit 10291e2e5d8cf7f9d6489821c164ec018547aac5
Author: openwebf-bot <openwebf@openwebf.com>
Date:   Mon Dec 2 12:14:17 2024 +0000

    Committing clang-format changes

commit 7a24a64ef8ae2ede6342b9e77a430447c31f0882
Author: andycall <andycall@openwebf.com>
Date:   Wed Nov 27 05:32:51 2024 +0800

    fix: fix text layout error.

commit 7143a8474a704c0c25de8ab4d455dbfd5c66bd03
Author: andycall <andycall@openwebf.com>
Date:   Mon Nov 25 19:20:21 2024 +0800

    doc: add annotations for WebFChildNodeSize.

commit 3e8f3af75d6e2741a2c4d9fd4c45cbe6ba7fd37e
Author: andycall <andycall@openwebf.com>
Date:   Mon Nov 25 15:59:44 2024 +0800

    fix: make listview elements to have WebFChildNodeSize.

commit 066ad2c0bd3c6d31c368fcb2dcc7872669d2b75d
Author: andycall <andycall@openwebf.com>
Date:   Mon Nov 25 15:17:38 2024 +0800

    feat: add WebFChildNodeSize widget.

commit 659e67a1dd4690199cdac77af991fdfd99ec5f5e
Author: Andy Dong <dongtiangche@outlook.com>
Date:   Thu Nov 28 18:33:15 2024 +0800

    feat: add console.inspect() API for inspecting JavaScript Objects. (#691)

    Add a new Console API for inspecting complex JavaScript objects.

    Example:
    ```javascript
    const json = {
        name: 1,
        age: '2',
        map: new Map(),
        set: new Set(),
        fn: function() { return 1; },
        undefined: undefined,
        null: null,
        nest: { nest: {aa: { arr: [1,2,3,4,5]}}}
      };
      json.map['name'] = new Map();
      json.set.add(1);
      json.set.add(2);
      json.map['name']['age'] = [1,2,3,4,5];
      console.inspect(json, 2, 3,4);
    ```

    Result:
    ```
    {
      name: 1,
      age: '2',
      map: Map {
        name: Map {
          age: [1, 2, 3, 4, 5]
        }
      },
      set: Set {1, 2},
      fn: Function {
        length: 0,
        name: 'fn',
        prototype: {
          constructor: #
        }
      },
      undefined: undefined,
      null: null,
      nest: {
        nest: {
          aa: {
            arr: [1, 2, 3, 4, 5]
          }
        }
      }
    } 2 3 4
    ```

commit bb23eb31030311df389d7a13f7032598ee211931
Author: Penner <penneryu@gmail.com>
Date:   Mon Nov 25 17:01:24 2024 +0800

    Fix: fix crash when add property maybe failed on build arguments

commit 97c34d9a3869b33f78e254ba5dfec0cf4969fa7b
Author: andycall <andycall@openwebf.com>
Date:   Sat Nov 23 15:58:24 2024 +0800

    fix: fix integration test.

commit 0bf6768bcb38f7cc519f352fb96a9bda3f7cb138
Author: andycall <andycall@openwebf.com>
Date:   Mon Nov 18 15:27:09 2024 +0800

    fix: fix test specs

commit ee5396cf37d028c2d3519ae830b47b58ce78e04b
Author: andycall <andycall@openwebf.com>
Date:   Tue Nov 12 19:04:53 2024 +0800

    fix: fix coordinate conversion related to position fixed.

* Committing clang-format changes

---------

Co-authored-by: openwebf-bot <openwebf@openwebf.com>